name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  security-events: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        

        
      - name: Build application
        run: npm run build
        
      - name: Build Electron app (Windows)
        if: matrix.os == 'windows-latest'
        run: npm run dist:win
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build Electron app (macOS)
        if: matrix.os == 'macos-latest'
        run: npm run dist:mac
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build Electron app (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: npm run dist:linux
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: List build outputs (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          echo "=== Windows build outputs ==="
          dir release-new
          if (Test-Path "release-new/nsis-web") {
            echo "NSIS Web outputs:"
            dir release-new/nsis-web
          }
          
      - name: List build outputs (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          echo "=== macOS build outputs ==="
          ls -la release-new/
          
      - name: List build outputs (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          echo "=== Linux build outputs ==="
          ls -la release-new/
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-build
          path: |
            release-new/
            dist/
            
  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          
      - name: List artifacts
        run: |
          echo "Available artifacts:"
          find artifacts -type f -name "*" | head -20
          
      - name: Verify Windows artifacts
        run: |
          echo "=== Windows artifacts ==="
          if [ -d "artifacts/windows-latest-build" ]; then
            echo "Windows build directory exists"
            ls -la artifacts/windows-latest-build/
            if [ -d "artifacts/windows-latest-build/release-new" ]; then
              echo "Windows release-new directory:"
              ls -la artifacts/windows-latest-build/release-new/
            fi
          else
            echo "Windows build directory not found"
          fi
          
      - name: Verify macOS artifacts
        run: |
          echo "=== macOS artifacts ==="
          if [ -d "artifacts/macos-latest-build" ]; then
            echo "macOS build directory exists"
            ls -la artifacts/macos-latest-build/
            if [ -d "artifacts/macos-latest-build/release-new" ]; then
              echo "macOS release-new directory:"
              ls -la artifacts/macos-latest-build/release-new/
            fi
          else
            echo "macOS build directory not found"
          fi
          
      - name: Verify Linux artifacts
        run: |
          echo "=== Linux artifacts ==="
          if [ -d "artifacts/ubuntu-latest-build" ]; then
            echo "Linux build directory exists"
            ls -la artifacts/ubuntu-latest-build/
            if [ -d "artifacts/ubuntu-latest-build/release-new" ]; then
              echo "Linux release-new directory:"
              ls -la artifacts/ubuntu-latest-build/release-new/
            fi
          else
            echo "Linux build directory not found"
          fi
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/windows-latest-build/release-new/*.exe
            artifacts/macos-latest-build/release-new/*.pkg
            artifacts/ubuntu-latest-build/release-new/*.AppImage
            artifacts/windows-latest-build/release-new/*.msi
            artifacts/ubuntu-latest-build/release-new/*.deb
            artifacts/ubuntu-latest-build/release-new/*.rpm
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  auto-update:
    needs: release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Setup update generation
        run: echo "Update files will be generated"
        
      - name: Generate update files
        run: |
          node -e "
            const version = process.env.GITHUB_REF.replace('refs/tags/v', '');
            const updateInfo = {
              version: version,
              files: [
                {
                  url: 'https://github.com/${{ github.repository }}/releases/download/v' + version + '/Gmail-Campaign-Desktop-' + version + '-win.exe',
                  sha512: 'placeholder',
                  size: 0
                },
                {
                  url: 'https://github.com/${{ github.repository }}/releases/download/v' + version + '/Gmail-Campaign-Desktop-' + version + '.pkg',
                  sha512: 'placeholder',
                  size: 0
                },
                {
                  url: 'https://github.com/${{ github.repository }}/releases/download/v' + version + '/Gmail-Campaign-Desktop-' + version + '.AppImage',
                  sha512: 'placeholder',
                  size: 0
                }
              ],
              path: 'Gmail-Campaign-Desktop-' + version + '-win.exe',
              sha512: 'placeholder',
              releaseDate: new Date().toISOString()
            };
            
            require('fs').writeFileSync('latest.yml', JSON.stringify(updateInfo, null, 2));
          "
          
      - name: Upload update file
        uses: actions/upload-artifact@v4
        with:
          name: update-info
          path: latest.yml
